name: Build & Release

# This workflow runs on pushes to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Use a matrix strategy to build on all three platforms
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        # actions/checkout@v5.0.1
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Set up Node.js
        # actions/setup-node@v6.0.0
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
        with:
          node-version: '24.11.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build and package application
        run: npm run build
        env:
          # This token is required for electron-builder to interact with GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}